optimize codes

diff --git a/templates/backup.sh.j2 b/templates/backup.sh.j2
--- a/templates/backup.sh.j2
+++ b/templates/backup.sh.j2
@@ -14,6 +14,19 @@ delete_time=`date  "+%Y%m%d" -d "-29 days"`
 
 eventslog_dir={{ eventslog_dir }}
 
+#向钉钉发送消息方法
+function SendMessageToDingding()
+{ # 发送钉钉消息
+Dingding_Url="{{ Dingding_Url }}" 
+curl "${Dingding_Url}" -H 'Content-Type: application/json' -d "
+ { \"msgtype\":\"text\",
+\"text\":{
+\"content\":\"${1}\"},
+\"at\":{
+\"atMobiles\":[\"15668661298\"],
+\"isAtAll\":false} }"
+}
+
 function backup() {
 
 #Save query digest to disk
@@ -26,9 +39,20 @@ sleep 7
 mysql -u admin -h 127.0.0.1 -P6032 --prompt='Admin> ' --default-auth=mysql_native_password \
 -e "set admin-stats_mysql_query_digest_to_disk=0;LOAD ADMIN VARIABLES TO RUNTIME;SAVE ADMIN VARIABLES TO DISK;"
 
-mysqldump -u admin -h 127.0.0.1 -P6032 --no-tablespaces --skip-triggers --single-transaction -B main > ${backupdir}/${hostname}_`date "+%Y%m%d_%H%M%S"`.sql
+mysqldump_version=`mysqldump -V|awk '{print $5}'|awk '{print substr($1,1,1)}'`
 
-find ${backupdir}/ -name "${hostname}_${delete_time}*" -exec rm -rf {} \;
+if [[ ${mysqldump_version} == 5 ]];then
+    mysqldump -u admin -h 127.0.0.1 -P6032 --no-tablespaces --skip-triggers --skip-add-locks -B main > ${backupdir}/${hostname}_`date "+%Y%m%d_%H%M%S"`.sql
+else
+    mysqldump -u admin -h 127.0.0.1 -P6032 --skip-column-statistics --no-tablespaces --skip-triggers --skip-add-locks -B main > ${backupdir}/${hostname}_`date "+%Y%m%d_%H%M%S"`.sql
+fi
+
+if [ $? -eq 0 ];then
+    echo "The Proxysql BackUp Successfully!"
+else
+    echo "The Proxysql BackUp Failure!"
+    SendMessageToDingding "The Proxysql {{ env }}_{{ ansible_hostname }}_{{ ansible_default_ipv4.address }} BackUp Failure!"
+fi
 
 }
 
@@ -43,6 +67,16 @@ zstd -T0 -v --rm ${filename}
 done
 
 }
+
+function purge_files_logs () {
+
+find ${backupdir}/ -name "${hostname}_${delete_time}*" -exec rm -rf {} \;
+
+find ${eventslog_dir}/ -mtime +30 -name "*" -exec rm -rf {} \;
+
+}
+
+purge_files_logs
 
 backup
 
